site_name: Epiphyte
site_url: https://mackelab.github.io/Epiphyte/

nav:
  - Home: index.md
  - Installation: install.md
  - Tutorials:
    - Launch a MySQL database locally: tutorials/1a. Launch a MySQL database locally.md
    - Launch a MySQL database on a virtual machine: tutorials/1b. Launch the MySQL database on a virtual machine.md
    - Attach a storage back-end to an existing database (optional): tutorials/2. (Optional) Attach a storage back-end to an existing database.md
    - Install Epiphyte: tutorials/3. Install Epiphyte locally or remotely.md
    - Configure and connect to a database: tutorials/4. Configure and connect to a database.md
    - Design and implement a database: tutorials/5. Design and implement a database.md
    - Develop an analysis workflow: tutorials/6. Develop an analysis workflow.md
    - Enable access for other users: tutorials/7. Enable access for other users.md
    - Run regular backups (optional): tutorials/8. Run regular backups (optional).md
    - Modify an existing database and workflow: tutorials/9. Modify an existing database and workflow.md
  - API Reference:
    - Database: reference/database.md
    - Data utilities: reference/data.md
    - Preprocessing: reference/preprocessing.md
  - Community:
    - Contributing: contribute.md
    - FAQ: faq.md
    - Acknowledgements: acknowledgements.md

theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: default
      primary: custom
      accent: custom

markdown_extensions:
  - extra
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - ../src
          options:
            show_source: true
            heading_level: 3
            members_order: source
            show_root_heading: true
            show_root_toc_entry: true
            show_symbol_type_toc: true
            separate_signature: true

watch:
  - ../src/epiphyte

extra_css:
  - stylesheets/extra.css

extra_javascript: []
